sudo: required

services:
  - docker

language: scala
scala: 2.11.7
jdk: oraclejdk8
before_script: 
  - ulimit -u 30000
  - chmod 777 gradlew
install: ./gradlew check --debug

after_success:
  - ./deploy.sh
